### ISSUE TITLE
How this extension works?

### ISSUE THREAD

**Issue by langpavel** [mattzeunert/immutable-object-formatter-extension#1]
Please, write some lines in readme :-) Thanks!

**Comment by mattzeunert** [comment]
I've pushed up the current code and added some info in the readme.

**Comment by JizongL** [comment]
I followed everything from your readme, but nothing is working.  do you have a tutorial to share?

**Comment by mattzeunert** [comment]
@JizongL Thanks for letting me know! Can tell me what version of Immutable.js you're using?
