### ISSUE TITLE
incorrectly displays Map properties of Records as Objects (Immutable 4.0.0-rc.9 only?)

### ISSUE THREAD

**Issue by jedwards1211** [mattzeunert/immutable-object-formatter-extension#10]
I'm using Immutable 4.0.0-rc.9, but I'm not sure whether this happens with Immutable 3.

![image](https://user-images.githubusercontent.com/1448194/34425028-f8c0dee0-ebed-11e7-9ba4-018a84f27c8f.png)

```
> console.log(Immutable);
(index):142 {default: {…}, version: "4.0.0-rc.9", Collection: ƒ, Iterable: ƒ, Seq: ƒ, …}
> const {Record, Map} = Immutable
undefined
> const Foo = Record({bar: Map()})
undefined
> Foo()
Record {
  bar: Object
    __proto__: Object
}
> Foo().get('bar')
Map[0]
```

**Comment by mattzeunert** [comment]
Yep, looks like this broke in 4.0.0-rc.9. If you update the extension in an hour or two it should be fine.

Thanks for reporting this!

**Comment by mattzeunert** [comment]
Looks like I need to make the same change to `Map` as well, will do soon.

**Comment by jedwards1211** [comment]
Cool, thanks for the quick response!
