### ISSUE TITLE
Privacy Concerns

### ISSUE THREAD

**Issue by dbchristopher** [mattzeunert/immutable-object-formatter-extension#11]
Hi, 

I noticed when installing this chrome extension, it required some very liberal content permissions. I.E. it can read and change *all your data* on the websites you visit.

![screen shot 2018-01-30 at 8 33 37 am](https://user-images.githubusercontent.com/238293/35578634-818644b2-0599-11e8-98f0-226ed0913bcf.png)

Can you explain why the object formatter requires such extreme permissions, and whether you can guarantee our data is safe? I will not be using the extension until those concerns are addressed. Thank you.

**Comment by mattzeunert** [comment]
Hi, Daniel!

Chrome's object formatter API works by adding formatters to `window.devtoolsFormatters`, which means the extension needs access to the global scope and with that also has access to all other content on the page. I'm not aware of a more restrictive API provided by Chrome.

There's no reporting or analytics in the extension, but if you want to be safe you can add [immutable-devtools](https://github.com/andrewdavey/immutable-devtools) to your project locally.

**Comment by dbchristopher** [comment]
Great, thanks so much for the explanation @mattzeunert!
