### ISSUE TITLE
1.8 version not work

### ISSUE THREAD

**Issue by pizn** [mattzeunert/immutable-object-formatter-extension#12]
When update to 1.8, it not working.

**Comment by mattzeunert** [comment]
Hey, thanks for reporting this!

Can you give an example of a page where it's not working?

**Comment by pizn** [comment]
Ok. I use macOS 10.13.3 and Chrome 64.0.3282.119, after upgrade to 1.8 it not working. Here is the example:

![image](https://user-images.githubusercontent.com/986480/35631645-62301718-06df-11e8-95f6-6fd73a2a86cd.png)

"Value" is an immutable value.

---
Maybe here is wrong? The dependency lost?
![image](https://user-images.githubusercontent.com/986480/35631879-0f5b99f8-06e0-11e8-8df6-ba141b43e328.png)

---

![image](https://user-images.githubusercontent.com/986480/35631944-3b420052-06e0-11e8-90f0-4d7d438a5811.png)

**Comment by mattzeunert** [comment]
How is that Map created? What version of Immutable are you using? I can fix this if you can provide a demo where I can reproduce the issue.

installDevTools doesn't need to be in global scope.

**Comment by wangxd18** [comment]
It seems like to be an issue showing Immutable Records.

**Comment by wangxd18** [comment]
The issue should be reproable for 3.x versions.

**Comment by wangxd18** [comment]
![image](https://user-images.githubusercontent.com/1212320/35703286-6a679d7c-0750-11e8-8f40-d5e88a304e36.png)

**Comment by mattzeunert** [comment]
Thanks both of you for reporting! It's fixed in 1.9 now.
