### ISSUE TITLE
instructions unclear

### ISSUE THREAD

**Issue by ha404** [mattzeunert/immutable-object-formatter-extension#13]
Screenshot doesn't match:
<img width="678" alt="screen shot 2018-02-23 at 5 55 28 pm" src="https://user-images.githubusercontent.com/567126/36624342-c613be84-18c2-11e8-8491-6e36b8a2f138.png">

**Comment by mattzeunert** [comment]
Those are the console settings, not the DevTools settings.

You're not the first one to be confused by this. I've updated the readme now to make the steps clearer: https://github.com/mattzeunert/immutable-object-formatter-extension/blob/master/README.md
