### ISSUE TITLE
When update to 1.9.1, it not working.

### ISSUE THREAD

**Issue by pizn** [mattzeunert/immutable-object-formatter-extension#17]
I use macOS 10.14.1 and Chrome 71.0.3578.80, after upgrade to 1.9.1 it not working. Here is the example:

![image](https://user-images.githubusercontent.com/986480/49697399-e99ef900-fbf1-11e8-8bbd-e9b605c7207e.png)

**Comment by mattzeunert** [comment]
Thanks, for pointing this out. Do you have an example page where the problem happens?

**Comment by marianoguerra** [comment]
It seems to happen with Records in 3.8.2, it doesn't happen with Records in 4.0.0-rc.12

This should reproduce it:

```
R = Immutable.Record({a: 1, b: 2}, 'MyRecord')
R();
```

**Comment by wizzard0** [comment]
same for me, 1.9.1, Chrome 72, "custom formatters" enabled, reproduceable as in previous comment, immutable-js 3.8.2, 4.0.0-rc12 both do not work

**Comment by mattzeunert** [comment]
Thanks everyone for reporting this! I forgot to publish the latest version of [immutable-devtools](https://github.com/andrewdavey/immutable-devtools) but had it linked locally on my old laptop. So when I published the Chrome extension from my new laptop it broke.

I've pushed a fix and it should be published on the Chrome web store in an hour.
