### ISSUE TITLE
Formatted objects in console are not accessible via keyboard

### ISSUE THREAD

**Issue by dougbacelar** [mattzeunert/immutable-object-formatter-extension#19]
I am used to navigate objects in the console using only my keyboard, but the formatted version of the immutable objects will not expand if you use your keyboard. You have to use your mouse to click through and expand the objects.

I am happy to submit a PR for this--could you please advise what is the best approach?

**Comment by mattzeunert** [comment]
Hey Doug, thanks for filing this!

I just tried this with a different custom formatter, and the behavior is the same. (I assume you use tab and arrow keys to navigate the object?)

I'd recommend [filing a bug on Chromium](Sign in - Google Accounts
https://crbug.com/wizard) for this.

Here's a minimal repro of the issue:

```
window.devtoolsFormatters = [{
    header: function(obj, config){
        return ["div", {}, "My Object " + obj.n]
    },
    hasBody: function(){
        return true;
    },
    body: function(obj, config){
        var elements = [["object", { object: {n: obj.n + 1}}]]
        return ["div", {}].concat(elements);
    }
}]
console.log({n: 1})
```

**Comment by dougbacelar** [comment]
@mattzeunert thank you very much for looking into it. I will use your repro and test it out this weekend.
