### ISSUE TITLE
keys are vertical-aligned to the center

### ISSUE THREAD

**Issue by oluckyman** [mattzeunert/immutable-object-formatter-extension#2]
<img width="552" alt="ss 2016-03-29 at 9 55 46 pm" src="https://cloud.githubusercontent.com/assets/642673/14120012/f053ab4a-f601-11e5-82fe-ac734f70acb7.png">
in https://github.com/andrewdavey/immutable-devtools screenshot keys are aligned to the top. So I’m wondering is it extension issue?

**Comment by mattzeunert** [comment]
The difference is that your state is a plain JavaScript object containing Immutable objects, whereas the screenshots show Immutable Record objects.

Apparently it's a general behavior of how custom object formatters interact with object keys - I've put another example below.

You can open an issue on the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=component%3APlatform%3EDevTools&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids) to see if aligning the values to the top is preferable.

<img width="446" alt="Backbone object formatter" src="https://cloud.githubusercontent.com/assets/1303660/14122812/3ed2fc06-f5f5-11e5-8946-a9fb28e915db.png">

**Comment by oluckyman** [comment]
Thanks. Opened the issue https://bugs.chromium.org/p/chromium/issues/detail?id=598982
