### ISSUE TITLE
Nested properties not showing up

### ISSUE THREAD

**Issue by melissjs** [mattzeunert/immutable-object-formatter-extension#21]
Great extension thank you so much Matt. I have had this issue for a few weeks now, when opening nested properties allI see is white. The work around is right clicking the object and selecting 'store as global variable' which can then be inspected at the bottom of the console. But this is inefficient... I have googled to see if others are having this issue and can't find any info - I know some other ppl are solving it the way I am right now too though. This does not happen with every object and I can't find the pattern for when it happens vs doesn't. This also happens when property values are extremely long and don't fit in the console window (resizing will fix it) but this isn't always the case.

Edit: I do think this has to do with line length. There are some values that are so long they would have to wrap even with the console window as wide as it can get and these are the ones that are not showing up.

![Screen Shot 2019-10-10 at 3 28 25 PM](https://user-images.githubusercontent.com/22379185/66608511-f83ca080-eb73-11e9-802b-d90bb904440a.png)

![Screen Shot 2019-10-10 at 3 28 42 PM](https://user-images.githubusercontent.com/22379185/66608513-f83ca080-eb73-11e9-9841-194d916f364f.png)

**Comment by AndrejGajdos** [comment]
+1

**Comment by ronatskiy** [comment]
+1

**Comment by mattzeunert** [comment]
Hey, thanks for reporting this!

I tried to replicate it, but wasn't able to. This is what I tried: 

1. Go to https://immutable-js.github.io/immutable-js/
2. Evaluate this in the console: `Immutable.fromJS({asfsdfsadf7348gy3u2ka: 2, asfsdfdasf234233223232323232323232323232323b: {c2738gy234342yt3fy3t32ggvmhgjsdagfadshfdagshfdhskgfkhjads: {xyz: "7348t67tit367tri762g332tyg2yf3j2ghf3hjgf32ghf3h32jhgf3gh2fg3f2hjfjhg32fhg2f3ghf2hfjh32fjh2fhg2fhg2fhg3fj2hgfgh23jf2gh3jf23ghf23hg3f2ghj2fjh32fgh23f2hj3g"}}})`

This is what I'm getting: 

![Screenshot 2019-10-23 at 21 40 07](https://user-images.githubusercontent.com/1303660/67432195-bb45c480-f5dd-11e9-818b-bf4b6b93104d.png)

Do you have repro steps? What Chrome version are you using?

**Comment by melissjs** [comment]
Interesting. When I follow your steps and use the console from the immutable page it looks like your screenshot. But in my own console I still see blank... this is my Chrome: Version 78.0.3904.70 (Official Build) (64-bit)

Thank you for looking into it, at least it is not an insurmountable problem...

**Comment by mattzeunert** [comment]
Next question then: what version of Immutable are you using?

**Comment by melissjs** [comment]
"immutable": "3.8.1",

**Comment by mattzeunert** [comment]
Hmm, I still can't replicate it with that version. If you've got a public page where that issue happens, let me know.

**Comment by melissjs** [comment]
Thank you again Matt

**Comment by linusthe3rd** [comment]
I am also encountering this issue. It is specifically happening in the debug panel in the Sources tab when looking at variables. If the panel is not wide enough, the values get hidden. I am guessing a recent change to Chrome around the time this issue was opened is the culprit.

<img width="518" alt="Image 2019-12-23 at 10 08 27 AM" src="https://user-images.githubusercontent.com/184709/71368034-5de1db80-256c-11ea-84dc-4081078d04b3.png">

**Comment by darwin** [comment]
https://github.com/binaryage/cljs-devtools/issues/52#issuecomment-531507102
