### ISSUE TITLE
Create new release for downstream changes in immutable-devtools

### ISSUE THREAD

**Issue by nbperry** [mattzeunert/immutable-object-formatter-extension#22]
There was an issue in the downstream immutable-devtools that was fixed here https://github.com/andrewdavey/immutable-devtools/pull/38 by @dbassett17. I just want to follow up and see if you could perhaps do a release of this extension to the chrome store with the updated dependency

` "immutable-devtools": "0.1.5"` or higher

**Comment by nbperry** [comment]
@mattzeunert just bumping this post

**Comment by mattzeunert** [comment]
Thanks @nbperry for the bump! I've upgraded to the latest version and published to the store.

They made some changes recently for extensions requiring broad permissions, but hopefully it'll get approved in a few days.

**Comment by nbperry** [comment]
New version appears to have gone out on the chrome store yesterday 4/20/2020 (Version 1.9.3). Thanks for publishing this.
