### ISSUE TITLE
possible way to determine if something is a record

### ISSUE THREAD

**Issue by jedwards1211** [mattzeunert/immutable-object-formatter-extension#4]
Not at all elegant, but this is `true` for Records (not sure if it's true for anything else though):
```js
Object.getPrototypeOf(Object.getPrototypeOf(Object.getPrototypeOf(thing)))['@@__IMMUTABLE_KEYED__@@']
```

**Comment by jedwards1211** [comment]
Oh nevermind, looks like you check `_defaultValues`.  The README sounded like you don't format records

**Comment by mattzeunert** [comment]
Thanks for the suggestions. I agree the readme didn't make that clear, I've updated it now.
