### ISSUE TITLE
Not seeing formatted results

### ISSUE THREAD

**Issue by jarekb84** [mattzeunert/immutable-object-formatter-extension#7]
I've installed the extension and enabled "Enable custom formatters" in chrome dev tool settings as per readme, but after doing so, I'm still not seeing the formatting in the screenshot. 

I'm using Chrome v56.0.2924.76 (64-bit) on a MBP. Is there anything else I'm missing to get this to work? My current console settings look like this.

![image](https://cloud.githubusercontent.com/assets/667983/22392724/271c4100-e4c2-11e6-8d76-d68b92576ac2.png)

**Comment by mattzeunert** [comment]
Yep, looks like the extension stopped working. I'll take a look soon.

**Comment by mattzeunert** [comment]
Actually, I can't replicate this. I'm aware of two situations where the extension wouldn't work:

- file:// URLs
- IFrames

Does either of those apply to you? Do you have a URL I can use for testing?

**Comment by jarekb84** [comment]
Yup, looks like I fall in the second situation. We've got our unit tests run in an iframe, which is where I was testing this extension out on. This extension works as expected when inspecting our prod code. 

Any plans to make this work with iframes?

**Comment by mattzeunert** [comment]
I've just published a new version that supports IFrames. Thanks for bringing up the issue!

**Comment by jarekb84** [comment]
Just tested and new version has the formatting. Thanks for adding this functionality so quickly!
