### ISSUE TITLE
ImmutableJS 4.0 breaks chrome extension

### ISSUE THREAD

**Issue by codekiln** [mattzeunert/immutable-object-formatter-extension#8]
I believe that an api change in 4.0 will break immutable object formatter extension. Try [this codepen](https://codepen.io/codekiln/pen/OxvBJJ?editors=0011) for an example of a record not being formatted in the chrome console when logged out. Instead, I get "Custom Formatter Failed: record.keySeq is not a function" and an unformatted object: 

![image](https://user-images.githubusercontent.com/140930/31335888-85c85338-acc2-11e7-92bd-0b52cc908243.png)

**Comment by mattzeunert** [comment]
Hi, Myer!

Thanks for reporting this, I'll fix it sometime this week.

**Comment by mattzeunert** [comment]
It's fixed now.
