### ISSUE TITLE
Missing "Enable custom formatters" checkbox

### ISSUE THREAD

**Issue by christiangenco** [mattzeunert/immutable-object-formatter-extension#9]
In Chrome Version 63.0.3239.108 (Official Build) (64-bit), the "Enable Custom formatters" checkbox is missing from the DevTools settings :

<img width="690" alt="screen shot 2017-12-27 at 3 06 57 pm" src="https://user-images.githubusercontent.com/179361/34393465-430daab8-eb18-11e7-9f12-048e70159e47.png">

Was it moved?

**Comment by mattzeunert** [comment]
Those are the console settings, the general DevTools settings are hidden behind the vertical `...`.

<img width="234" alt="screen shot 2017-12-28 at 20 12 06" src="https://user-images.githubusercontent.com/1303660/34410457-74371748-ec0b-11e7-9120-f641b09dada5.png">

**Comment by christiangenco** [comment]
Ahh, found it:

<img width="1440" alt="screen shot 2018-01-04 at 4 46 03 pm" src="https://user-images.githubusercontent.com/179361/34587644-c7476ce0-f16e-11e7-8541-d671241eabf5.png">

Thank you!

**Comment by herbowicz** [comment]
Custom formatters are no longer supported in the latest Chrome (84+). More info:
https://github.com/binaryage/cljs-devtools/issues/55#issuecomment-632384007
